kind: Service
apiVersion: v1
spec:
  selector:
    app: express-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
metadata:
  name: express-app-service
  namespace: default
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: express-app-deployment
  namespace: default
  labels:
    app: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      namespace: default
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: localhost:5000/express-app:1.0.0
        ports:
        - name: app
          containerPort: 8080

