apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: "gcr.io/knative-samples/helloworld-python"
            env:
              - name: "TARGET"
                value: "world"