apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
    - image: 'express-app'
      context: example
      docker:
        dockerfile: config/app/dev/Dockerfile
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: false
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
      - example/app.yml
